// URL deve ser configurada via config.local.js (não comitar)
// Copie config.local.js.example para config.local.js e configure a URL
const LOCAL_CONFIG = window.LOCAL_CONFIG || {};

const CONFIG = {
  pollMs: 60000,
  cacheMinutes: 10,
  maxLatest: 25,
  proxyUrl: LOCAL_CONFIG.proxyUrl || "",
  // Token removido - autenticação agora é feita via session token do servidor
  sites: [
    { key: "datageoparana", name: "Datageo Parana", kind: "datageo" },
    { key: "portfolio", name: "Portfolio", kind: "portfolio" },
    { key: "vbp-parana", name: "VBP Parana", kind: "vbp" },
    { key: "precos-florestais", name: "Precos Florestais", kind: "precos" },
    { key: "precos-terras", name: "Precos de Terras", kind: "precos" },
    { key: "precos-diarios", name: "Precos Diarios", kind: "precos" },
    { key: "comexstat-parana", name: "ComexStat Parana", kind: "comex" },
    { key: "emprego-agro-parana", name: "Emprego Agro Parana", kind: "emprego" },
    { key: "censo-parana", name: "Censo Parana", kind: "censo" },
    { key: "credito-rural-parana", name: "Credito Rural Parana", kind: "credito" },
    { key: "saude-parana", name: "Saude Parana", kind: "saude" },
    { key: "seguranca-parana", name: "Seguranca Parana", kind: "seguranca" },
    { key: "cwbtopo", name: "CWB Topografia", kind: "cwbtopo" },
    { key: "c2-parana", name: "C2 Parana", kind: "c2parana" },
  ],
};

// Field schemas for each site type - eliminates magic strings in normalizers
const FIELD_SCHEMAS = {
  datageo: {
    timestamp: ["timestamp", "Timestamp"],
    url: ["page", "Page", "url", "URL"],
    path: ["pathname", "Pathname", "path"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone"],
    sessionId: ["sessionId", "Session ID", "session id"],
    userAgent: ["userAgent", "User Agent", "user agent"],
    os: [],
    browser: [],
    deviceType: ["deviceType", "Device Type", "device"],
    language: ["language", "Language"],
    screenWidth: ["screenWidth", "Screen Width"],
    screenHeight: ["screenHeight", "Screen Height"],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["loadTime", "LoadTime", "Load Time"],
    firstContentfulPaint: ["firstContentfulPaint", "FirstContentfulPaint"],
    domInteractiveTime: ["domInteractiveTime", "DomInteractiveTime"],
    isMobile: ["isMobile", "Is Mobile"],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme", "colorScheme"],
  },
  portfolio: {
    timestamp: ["Client Timestamp", "Timestamp", "client timestamp", "timestamp"],
    url: ["Page URL", "URL", "page url", "url", "page"],
    path: ["pathname", "Pathname", "path"],
    referrer: ["Referrer", "referrer"],
    timezone: ["Timezone", "timezone"],
    sessionId: ["Session ID", "session id", "sessionId"],
    userAgent: ["User Agent", "user agent", "userAgent"],
    os: ["os", "OS", "Sistema Operacional"],
    browser: ["browser", "Browser", "Navegador"],
    deviceType: ["deviceType", "Device Type", "device", "Device"],
    language: ["Language", "language"],
    screenWidth: ["Screen Width", "screenWidth", "screenResolution"],
    screenHeight: ["Screen Height", "screenHeight"],
    connectionType: ["Connection Type", "connectionType"],
    loadTime: ["Page Load Time (ms)", "Page Load Time", "pageLoadTime", "loadTime", "LoadTime"],
    firstContentfulPaint: ["First Contentful Paint", "firstContentfulPaint", "FirstContentfulPaint"],
    domInteractiveTime: ["DOM Interactive Time", "domInteractiveTime", "DomInteractiveTime"],
    isMobile: ["isMobile", "Is Mobile"],
    utmSource: ["UTM Source", "utmSource"],
    utmMedium: ["UTM Medium", "utmMedium"],
    utmCampaign: ["UTM Campaign", "utmCampaign"],
    utmTerm: ["UTM Term", "utmTerm"],
    utmContent: ["UTM Content", "utmContent"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme", "colorScheme"],
  },
  precos: {
    timestamp: ["Timestamp", "timestamp"],
    url: ["URL", "url", "page"],
    path: ["Caminho", "caminho", "pathname", "Pathname"],
    referrer: ["Referrer", "referrer"],
    timezone: ["Timezone", "timezone"],
    sessionId: ["Session ID", "session id", "sessionId"],
    userAgent: ["User Agent", "user agent", "userAgent"],
    os: ["os", "OS", "Sistema Operacional", "sistema operacional"],
    browser: ["browser", "Browser", "Navegador", "navegador"],
    deviceType: ["deviceType", "Device Type", "Dispositivo", "dispositivo"],
    language: ["language", "Language", "Idioma"],
    screenWidth: ["screenWidth", "Screen Width"],
    screenHeight: ["screenHeight", "Screen Height"],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["LoadTime", "loadTime", "Load Time"],
    firstContentfulPaint: ["firstContentfulPaint", "FirstContentfulPaint", "First Contentful Paint"],
    domInteractiveTime: ["domInteractiveTime", "DomInteractiveTime", "DOM Interactive Time"],
    isMobile: ["isMobile", "Is Mobile"],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme", "colorScheme"],
  },
  comex: {
    timestamp: ["timestamp", "Timestamp"],
    url: ["page", "URL", "url"],
    path: ["pathname", "Pathname"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone"],
    sessionId: ["sessionId", "Session ID", "session id"],
    userAgent: ["userAgent", "User Agent", "user agent"],
    os: [],
    browser: [],
    deviceType: ["deviceType", "Device Type", "device"],
    language: ["language", "Language"],
    screenWidth: ["screenWidth", "Screen Width"],
    screenHeight: ["screenHeight", "Screen Height"],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["loadTime", "LoadTime", "Load Time"],
    firstContentfulPaint: ["firstContentfulPaint", "FirstContentfulPaint"],
    domInteractiveTime: ["domInteractiveTime", "DomInteractiveTime"],
    isMobile: ["isMobile", "Is Mobile"],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme", "colorScheme"],
  },
  emprego: {
    timestamp: ["timestamp", "Timestamp"],
    url: ["page", "URL", "url"],
    path: ["pathname", "Pathname"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone"],
    sessionId: ["sessionId", "Session ID", "session id"],
    userAgent: [],
    os: [],
    browser: [],
    deviceType: ["deviceType", "Device Type", "Dispositivo"],
    language: ["language", "Language"],
    screenWidth: [],
    screenHeight: [],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["loadTime", "LoadTime", "Load Time"],
    firstContentfulPaint: [],
    domInteractiveTime: [],
    isMobile: [],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme"],
  },
  vbp: {
    timestamp: ["timestamp", "Timestamp", "Date", "date"],
    url: ["url", "URL", "Page URL", "page"],
    path: ["pathname", "path"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone", "Fuso Horario", "Fuso horário", "Fuso", "Time Zone", "time zone", "tz", "K", "k"],
    timezonePattern: /(fuso|time\s*zone|timezone|tz)/i,
    sessionId: ["sessionId", "Session ID", "session id"],
    userAgent: ["userAgent", "User Agent", "user agent"],
    os: ["os", "OS", "Sistema Operacional"],
    browser: ["browser", "Browser", "Navegador"],
    deviceType: ["deviceType", "Device Type", "device", "Device", "Dispositivo"],
    language: ["language", "Language"],
    screenWidth: ["screenWidth", "Screen Width"],
    screenHeight: ["screenHeight", "Screen Height"],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["LoadTime", "loadTime", "Load Time"],
    firstContentfulPaint: ["firstContentfulPaint", "FirstContentfulPaint", "First Contentful Paint"],
    domInteractiveTime: ["domInteractiveTime", "DomInteractiveTime", "DOM Interactive Time"],
    isMobile: ["isMobile", "Is Mobile"],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme", "colorScheme"],
  },
  censo: {
    timestamp: ["timestamp", "Timestamp"],
    url: ["page", "URL", "url"],
    path: ["pathname", "Pathname"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone"],
    sessionId: [],
    userAgent: [],
    os: [],
    browser: [],
    deviceType: ["deviceType", "Device Type", "Dispositivo"],
    language: ["language", "Language"],
    screenWidth: [],
    screenHeight: [],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["loadTime", "LoadTime", "Load Time"],
    firstContentfulPaint: [],
    domInteractiveTime: [],
    isMobile: [],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme"],
  },
  credito: {
    timestamp: ["timestamp", "Timestamp"],
    url: ["page", "URL", "url"],
    path: ["pathname", "Pathname"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone"],
    sessionId: [],
    userAgent: [],
    os: [],
    browser: [],
    deviceType: ["deviceType", "Device Type", "Dispositivo"],
    language: ["language", "Language"],
    screenWidth: [],
    screenHeight: [],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["loadTime", "LoadTime", "Load Time"],
    firstContentfulPaint: [],
    domInteractiveTime: [],
    isMobile: [],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme"],
  },
  saude: {
    timestamp: ["timestamp", "Timestamp"],
    url: ["page", "URL", "url"],
    path: ["pathname", "Pathname"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone"],
    sessionId: [],
    userAgent: [],
    os: [],
    browser: [],
    deviceType: ["deviceType", "Device Type", "Dispositivo"],
    language: ["language", "Language"],
    screenWidth: [],
    screenHeight: [],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["loadTime", "LoadTime", "Load Time"],
    firstContentfulPaint: [],
    domInteractiveTime: [],
    isMobile: [],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme"],
  },
  seguranca: {
    timestamp: ["timestamp", "Timestamp"],
    url: ["page", "URL", "url"],
    path: ["pathname", "Pathname"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone"],
    sessionId: [],
    userAgent: [],
    os: [],
    browser: [],
    deviceType: ["deviceType", "Device Type"],
    language: ["language", "Language"],
    screenWidth: [],
    screenHeight: [],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["loadTime", "LoadTime", "Load Time"],
    firstContentfulPaint: [],
    domInteractiveTime: [],
    isMobile: [],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme"],
  },
  cwbtopo: {
    timestamp: ["timestamp", "Timestamp"],
    url: ["page", "URL", "url"],
    path: ["pathname", "Pathname"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone"],
    sessionId: [],
    userAgent: [],
    os: [],
    browser: [],
    deviceType: ["deviceType", "Device Type"],
    language: ["language", "Language"],
    screenWidth: [],
    screenHeight: [],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["loadTime", "LoadTime", "Load Time"],
    firstContentfulPaint: [],
    domInteractiveTime: [],
    isMobile: [],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme"],
  },
  c2parana: {
    timestamp: ["timestamp", "Timestamp"],
    url: ["page", "URL", "url"],
    path: ["pathname", "Pathname"],
    referrer: ["referrer", "Referrer"],
    timezone: ["timezone", "Timezone"],
    sessionId: [],
    userAgent: [],
    os: [],
    browser: [],
    deviceType: ["deviceType", "Device Type", "Dispositivo"],
    language: ["language", "Language"],
    screenWidth: [],
    screenHeight: [],
    connectionType: ["connectionType", "Connection Type"],
    loadTime: ["loadTime", "LoadTime", "Load Time"],
    firstContentfulPaint: [],
    domInteractiveTime: [],
    isMobile: [],
    utmSource: ["utmSource", "UTM Source"],
    utmMedium: ["utmMedium", "UTM Medium"],
    utmCampaign: ["utmCampaign", "UTM Campaign"],
    utmTerm: ["utmTerm", "UTM Term"],
    utmContent: ["utmContent", "UTM Content"],
    pageTitle: ["pageTitle", "Page Title", "title", "Title"],
    screenOrientation: ["screenOrientation", "Screen Orientation"],
    prefersColorScheme: ["prefersColorScheme", "Prefers Color Scheme"],
  },
};

// Returning visitor field variations
const RETURNING_FIELDS = [
  "Returning Visitor", "returning visitor", "Returning", "returning",
  "ReturningVisitor", "returningVisitor", "Returning_Visitor", "returning_visitor",
  "Is Returning", "isReturning", "is_returning",
  "Visitante Recorrente", "visitante recorrente",
  "Retornando", "retornando", "Retorno", "retorno",
];
const RETURNING_PATTERN = /(return|retorn)/i;

// Timezone to region mapping for geographic visualization
const TIMEZONE_REGIONS = {
  "America/Sao_Paulo": { region: "Brasil", subregion: "Sudeste", flag: "🇧🇷" },
  "America/Cuiaba": { region: "Brasil", subregion: "Centro-Oeste", flag: "🇧🇷" },
  "America/Manaus": { region: "Brasil", subregion: "Norte", flag: "🇧🇷" },
  "America/Recife": { region: "Brasil", subregion: "Nordeste", flag: "🇧🇷" },
  "America/Fortaleza": { region: "Brasil", subregion: "Nordeste", flag: "🇧🇷" },
  "America/Bahia": { region: "Brasil", subregion: "Nordeste", flag: "🇧🇷" },
  "America/Belem": { region: "Brasil", subregion: "Norte", flag: "🇧🇷" },
  "America/Porto_Velho": { region: "Brasil", subregion: "Norte", flag: "🇧🇷" },
  "America/Campo_Grande": { region: "Brasil", subregion: "Centro-Oeste", flag: "🇧🇷" },
  "America/Boa_Vista": { region: "Brasil", subregion: "Norte", flag: "🇧🇷" },
  "America/Rio_Branco": { region: "Brasil", subregion: "Norte", flag: "🇧🇷" },
  "America/Noronha": { region: "Brasil", subregion: "Nordeste", flag: "🇧🇷" },
  "America/New_York": { region: "EUA", subregion: "Leste", flag: "🇺🇸" },
  "America/Los_Angeles": { region: "EUA", subregion: "Oeste", flag: "🇺🇸" },
  "America/Chicago": { region: "EUA", subregion: "Centro", flag: "🇺🇸" },
  "America/Denver": { region: "EUA", subregion: "Montanhas", flag: "🇺🇸" },
  "Europe/London": { region: "Europa", subregion: "Reino Unido", flag: "🇬🇧" },
  "Europe/Paris": { region: "Europa", subregion: "Franca", flag: "🇫🇷" },
  "Europe/Berlin": { region: "Europa", subregion: "Alemanha", flag: "🇩🇪" },
  "Europe/Madrid": { region: "Europa", subregion: "Espanha", flag: "🇪🇸" },
  "Europe/Lisbon": { region: "Europa", subregion: "Portugal", flag: "🇵🇹" },
  "Europe/Rome": { region: "Europa", subregion: "Italia", flag: "🇮🇹" },
  "Asia/Tokyo": { region: "Asia", subregion: "Japao", flag: "🇯🇵" },
  "Asia/Shanghai": { region: "Asia", subregion: "China", flag: "🇨🇳" },
  "Asia/Singapore": { region: "Asia", subregion: "Singapura", flag: "🇸🇬" },
  "Australia/Sydney": { region: "Oceania", subregion: "Australia", flag: "🇦🇺" },
  "America/Buenos_Aires": { region: "America do Sul", subregion: "Argentina", flag: "🇦🇷" },
  "America/Santiago": { region: "America do Sul", subregion: "Chile", flag: "🇨🇱" },
  "America/Lima": { region: "America do Sul", subregion: "Peru", flag: "🇵🇪" },
  "America/Bogota": { region: "America do Sul", subregion: "Colombia", flag: "🇨🇴" },
  "America/Mexico_City": { region: "America do Norte", subregion: "Mexico", flag: "🇲🇽" },
};

// Color palette for charts - distinct colors per site
const CHART_COLORS = {
  sites: [
    "#10b981", // Datageo Parana - Verde esmeralda
    "#f59e0b", // Portfolio - Ambar
    "#3b82f6", // VBP Parana - Azul
    "#22c55e", // Precos Florestais - Verde
    "#a855f7", // Precos de Terras - Roxo
    "#ef4444", // Precos Diarios - Vermelho
    "#06b6d4", // ComexStat Parana - Ciano
    "#ec4899", // Emprego Agro Parana - Rosa
    "#8b5cf6", // Censo Parana - Violeta
    "#0369a1", // Credito Rural Parana - Sky Blue
    "#14b8a6", // Saude Parana - Teal
    "#475569", // Seguranca Parana - Slate
    "#d97706", // CWB Topografia - Amber escuro
    "#f97316", // C2 Parana - Laranja (command & control)
  ],
  doughnut: ["#10b981", "#f59e0b", "#3b82f6", "#a855f7", "#ef4444", "#06b6d4", "#ec4899", "#8b5cf6", "#0369a1", "#14b8a6", "#475569", "#d97706", "#f97316"],
  heatmap: {
    min: "rgba(45, 212, 191, 0.1)",
    max: "rgba(255, 122, 24, 0.9)",
  },
};

// Site color map for quick lookup
const SITE_COLORS = {
  "datageoparana": "#10b981",
  "portfolio": "#f59e0b",
  "vbp-parana": "#3b82f6",
  "precos-florestais": "#22c55e",
  "precos-terras": "#a855f7",
  "precos-diarios": "#ef4444",
  "comexstat-parana": "#06b6d4",
  "emprego-agro-parana": "#ec4899",
  "censo-parana": "#8b5cf6",
  "credito-rural-parana": "#0369a1",
  "saude-parana": "#14b8a6",
  "seguranca-parana": "#475569",
  "cwbtopo": "#d97706",
  "c2-parana": "#f97316",
};

// Days of week in Portuguese
const DAYS_PT = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"];
